### ISSUE TITLE
Do we explicitly need to have default values for message fields?

### ISSUE THREAD

**Issue by Aniket21mathur** [Aniket21mathur/Chapel-protobuf#9]
Do we need the plugin to explicitly define a default value for each message field?

**Comment by Aniket21mathur** [comment]
Since, every proto message field is mapped to a corresponding chapel type, I don't find it necessary and so far I have not seen any protobuf requirement depending on this. 

@mppf @lydia-duncan @astatide comments?

**Comment by Aniket21mathur** [comment]
This issue points to this https://github.com/Aniket21mathur/Chapel-protobuf/blob/master/src/plugin/field_base.cc#L49, basically.

**Comment by mppf** [comment]
Just so I understand - are you saying that the plugin currently generates a default for each message field, but you are not sure if it should do so?

Generally speaking I find it easier to talk about something like this from a user viewpoint. Can you show an example with a protobuf file & example generated code & what you imagine the user would write? Can we use this user viewpoint to answer the question?

It would seem to me that this question amounts to what initializers are available on the generated message types, and, in particular, if message types can be default-initialized.

**Comment by Aniket21mathur** [comment]
> Just so I understand - are you saying that the plugin currently generates a default for each message field, but you are not sure if it should do so?

Currently, the plugin does not add any default values to message types. The code that I pointed to is not being used anywhere for now.

> Generally speaking I find it easier to talk about something like this from a user viewpoint. Can you show an example with a protobuf file & example generated code & what you imagine the user would write? Can we use this user viewpoint to answer the question?

Explicitly defining a variable's type in Chapel, assigns it a default value. From my point of view, I don't see any need to have explicit default values from the plugin side. A user will assign values to all/some fields  of the message and the other fields should be default initialized I guess.

**Comment by mppf** [comment]
> Explicitly defining a variable's type in Chapel, assigns it a default value. From my point of view, I don't see any need to have explicit default values from the plugin side. A user will assign values to all/some fields of the message and the other fields should be default initialized I guess.

Right, there are several options here:

1. Message types have no default value. Users must `new` them and specify all fields. (I don't think we want this).
2. Message types rely on the compiler-generated initializer and default values based on the types. It is my understanding this is what is happening now. For numeric types and string/bytes this is fine. It can be harder with things like `owned SomeClass` which have no default value.
3. Message types include explicit default values for fields. While this would inform the compiler-generated initializer, I don't see a reason to do this. The user-facing functionality is the same as in 3.
4. Message types include explicit initializers, so `proc init() { ... }` and `proc init(field1: field1Type, ...)` are generated. I don't see why we would do this instead of using the compiler-generated initializer.

**Comment by Aniket21mathur** [comment]
@mppf I think the discussion is diverted towards messages being used as fields in other messages like ->

```
message a {
  int64 x = 1;
}

message b {
  repeated a var = 1;
}
``` 
We have not implemented this yet, from this issue I was just asking wether to have default values for simple types like (`uint64`, `bool`, `bytes`, etc) from the plugin side or to let them being default assigned from Chapel . For example, currently we have -> 

```
  var b_: uint(64) ;
  proc b { return b_; }
  proc ref b ref { return b_; }
```
or we can do ->

```
  var b_: uint(64) = someDefaultValueFromThePlugin ;
  proc b { return b_; }
  proc ref b ref { return b_; }
```

I have no problem going with what we are doing currently.



> Right, there are several options here:

Though the options you provided will be really useful when we will add support for messages to be used as fields.
